name: lmar_learn
description: A learning app that empowers minds through inclusive education.
publish_to: 'none'

version: 1.0.0+1

# --------------------------------------------------
# Environment
# --------------------------------------------------
environment:
  sdk: '>=3.10.0 <4.0.0'

# --------------------------------------------------
# Dependencies
# --------------------------------------------------
dependencies:
  flutter:
    sdk: flutter

  # ---------------------------
  # UI + Theming
  # ---------------------------
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  carousel_slider: ^5.1.1
  loading_animation_widget: ^1.2.0
  fluttertoast: ^9.0.0
  flutter_typeahead: ^5.0.0
  shimmer: ^3.0.0  
  fluent_ui: ^4.13.0

  # ---------------------------
  # Chart
  # ---------------------------
  fl_chart: ^1.1.1
  #charts_flutter_new:  ^0.12.0

  # ---------------------------
  # State Management
  # ---------------------------
  provider: ^6.1.2

  # ---------------------------
  # Firebase Services
  # ---------------------------
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4

  # ---------------------------
  # Local Storage
  # ---------------------------
  shared_preferences: ^2.3.2

  # ---------------------------
  # Localization
  # ---------------------------
  flutter_localizations:
    sdk: flutter

  # ---------------------------
  # Utilities & Tools
  # ---------------------------
  http: ^1.2.2
  url_launcher: ^6.3.1
  path: ^1.9.1
  stack_trace: ^1.12.1
  logger: ^2.6.2
  json_rpc_2: ^4.0.0
  web: ^1.1.1
  dtd: ^4.0.0

  # ---------------------------
  # Desktop Window Control
  # ---------------------------
  window_size: ^0.1.0

# --------------------------------------------------
# Development Dependencies
# --------------------------------------------------
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# --------------------------------------------------
# Flutter Configurations
# --------------------------------------------------
flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/pictures/
    - assets/courseimages/
